[".config/k9s/skins"]
  type = "archive"
  url = "https://github.com/catppuccin/k9s/archive/main.tar.gz"
  exact = true
  refreshPeriod = "168h"
  stripComponents = 2
  path = "k9s-main/dist"
[".config/lazygit/config.yml"]
  type = "archive-file"
  url = "https://github.com/catppuccin/lazygit/archive/refs/tags/v2.2.0.tar.gz"
  exact = true
  refreshPeriod = "168h"
  stripComponents = 2
  path = "mocha/mauve.yml"
[".local/share/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".local/share/zsh-autosuggestions"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
