[tools]
1password = "latest"
chezmoi = "latest"
envsubst = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
gitleaks = "latest"
go = "1.25"
helm = "latest"
jq = "latest"
jqp = "latest"
jwtui = "latest"
k9s = "latest"
kubectl = "latest"
kubelogin = "latest"
lazygit = "latest"
neovim = "latest"
node = "24"
pre-commit = "latest"
python = "3"
ripgrep = "latest"
starship = "latest"
uv = "latest"
vault = "latest"
yq = "latest"
zoxide = "latest"
